### ISSUE TITLE
missing WIF CHARACTERS

### ISSUE THREAD

**Issue by Handsomekaizer** [cosmoio/bitcoin_key_recovery#2]
Hello sir
Sorry to bother I was just going through your repo to see if you could help me. The problem I have is with my wallet private key characters, I mistakenly damaged the piece of paper I wrote it on, so I was wondering if you could help me write a program that will brute Force all the 10 missing characters very fast and find the correct characters and in return I will make a donation of 2 BTC to you if I find the correct keys

**Comment by cosmoio** [comment]
Hello,

hmm 10 missing characters in hex? Assuming hex, that's 16^10 combinations, that*s quite a few iterations to try. I reckon creating a public key per iterated private key and testing it .. this will likely not be fast, certainly not a million tries per second which would be necessary to iterate through all possibilities in days. I will think about it, are you in a hurry?

Cheers,
Mat

-----
Security Analyst & Programmer

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by cosmoio** [comment]
Hello,

please send your public key for me to verify that you have sufficient funds for any potential bounty and some sort of verification that the coins really belong to you. I'm happy to help you but it is important that any potential code mustn't be misused to brute force anything that does not belong to you!

Again I have to ask, are you in a hurry? Given that BTCs are currently quite far from the ath you probably don't need access right away?

Cheers,
Mat

-----
Security Analyst & Programmer

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Handsomekaizer** [comment]
It is not in hex it is in base 58, I have an idea is it possible for you to
create a program  maybe in html , JavaScript or typescript, go or php that
fills in the missing characters in the place there are missing (the place
Missing will be marked ** or ??) And the program will automatically
generate millions of  alphanumeric characters and save it in form of txt
that will be randomly checked to see if any of the combination is correct
or has balance.

**Comment by cosmoio** [comment]
Hey,

what's you bitcoin address? I would like to check whether there are funds. Then send me the encoded private key including missing characters. THEN I will have to have a look to see what is possible ...

"It is not in hex it is in base 58, I have an idea is it possible for you to
create a program maybe in html , JavaScript or typescript, go or php that
fills in the missing characters in the place there are missing (the place
Missing will be marked ** or ??) And the program will automatically
generate millions of alphanumeric characters and save it in form of txt
that will be randomly checked to see if any of the combination is correct
or has balance."

There might already be tooling available, but I have to see the problem first.
Since Bitcoin aren't worth much at the moment (= crypto winter) we have time for this problem anyway.

Cheers,
Mat
-----
Security Analyst & Programmer

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
